//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlumniPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class alum_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public alum_tbl()
        {
            this.cv_tbl = new HashSet<cv_tbl>();
        }
    
        public string alum_num { get; set; }
        public string dept_id { get; set; }
        public string alum_name { get; set; }
        public string alum_sex { get; set; }
        public System.DateTime alum_bdate { get; set; }
        public int yr_grad { get; set; }
        public string alum_email { get; set; }
        public string alum_con { get; set; }
        public string alum_password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cv_tbl> cv_tbl { get; set; }
    }
}
