//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlumniPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comp_acc_tbl
    {
        public int comp_acc_id { get; set; }
        public int user_id { get; set; }
        public int comp_id { get; set; }
        public string comp_email { get; set; }
    }
}
