//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlumniPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class event_tbl
    {
        public int event_id { get; set; }
        public string admin_id { get; set; }
        public string event_name { get; set; }
        public string event_desc { get; set; }
        public System.DateTime event_date { get; set; }
        public System.DateTime event_post_date { get; set; }
        public string event_loc { get; set; }
    }
}
