//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlumniPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class event_reg_tbl
    {
        public int event_reg_id { get; set; }
        public int user_id { get; set; }
        public int event_id { get; set; }
        public System.DateTime regis_date { get; set; }
    }
}
