//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlumniPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class job_post_tbl
    {
        public int job_id { get; set; }
        public int comp_id { get; set; }
        public string job_title { get; set; }
        public string job_target { get; set; }
        public string job_loc { get; set; }
        public string job_specs { get; set; }
        public string job_salary { get; set; }
        public string job_type { get; set; }
        public System.DateTime job_post_date { get; set; }
        public System.DateTime job_deadline { get; set; }
    
        public virtual comp_tbl comp_tbl { get; set; }
    }
}
