//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlumniPortal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AlumPortalDbEntities : DbContext
    {
        public AlumPortalDbEntities()
            : base("name=AlumPortalDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin_acc_tbl> admin_acc_tbl { get; set; }
        public virtual DbSet<admin_tbl> admin_tbl { get; set; }
        public virtual DbSet<alum_acc_tbl> alum_acc_tbl { get; set; }
        public virtual DbSet<comp_acc_tbl> comp_acc_tbl { get; set; }
        public virtual DbSet<event_reg_tbl> event_reg_tbl { get; set; }
        public virtual DbSet<user_tbl> user_tbl { get; set; }
        public virtual DbSet<cv_tbl> cv_tbl { get; set; }
        public virtual DbSet<job_post_tbl> job_post_tbl { get; set; }
        public virtual DbSet<alum_tbl> alum_tbl { get; set; }
        public virtual DbSet<dept_tbl> dept_tbl { get; set; }
        public virtual DbSet<comp_tbl> comp_tbl { get; set; }
        public virtual DbSet<event_tbl> event_tbl { get; set; }
    }
}
